services:
  # 1. Laravel PHP-FPM Application
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net

  # 2. Web Server (Nginx)
  nginx:
    image: nginx:trixie-perl
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  # 3. Database (MySQL)
  db:
    image: mysql:latest
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

  # 4. Cache, Queue & JSON (Full Redis Stack)
  redis:
    # 'redis-stack' has Insight GUI enabled by default
    image: redis/redis-stack:latest 
    container_name: laravel_redis
    ports:
      - "6379:6379"  # Database
      - "8001:8001"  # RedisInsight Dashboard
    volumes:
      - redis_data:/data
    networks:
      - laravel_net

  # 5. Email Testing Tool (Mailpit)
  mailpit:
    image: axllent/mailpit:latest
    container_name: laravel_mail
    ports:
      - "8025:8025"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  mysql_data:
  redis_data: